apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-instance-deployment
spec:
  selector:
    matchLabels:
      app: jenkins-instance
  template:
    metadata:
      labels:
        app: jenkins-instance
    spec:
      containers:
        - name: jenkins-instance
          image: ibrahimgokyar/opendartrepo:spring-boot-telekomV04
          imagePullPolicy: Always
          ports:
            - containerPort: 8085