apiVersion: v1
kind: Service
metadata:
  name: jenkins-instance-service
  labels:
    app: jenkins-instance
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.0.10
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
  selector:
    app: jenkins-instance